In [1]:
import torch

x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [14]:
x.requires_grad_(True)
print(x.grad)

None


In [15]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [17]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [18]:
# 导数 (2x^2)' = 4x，torch 计算结果跟我们的期望一样
x.grad == 4 * x

tensor([True, True, True, True])

In [23]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [56]:
print(x)
x.grad.zero_()
# y = x[0]*x[2] + x[1]*x[2] + x[2]*x[2] + x[3]*x[2]
y = x * x
y.backward(torch.tensor([1, 1, 1, 1.0]))
# y'_x[0] = x[2], y'_x[1] = x[2], y'_x[2] = 2*x[2]+x[0]+x[1]+x[3], y'_x[3] = x[2]
x.grad
# See more at: https://zhuanlan.zhihu.com/p/51385110

tensor([0., 1., 2., 3.], requires_grad=True)


tensor([0., 2., 4., 6.])

In [51]:
x.grad.zero_()
y = x * x
u = y.detach()
# u 可以看做是一个常数，和 x 不相关
z = u * x

z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [58]:
x.grad.zero_()
y = x * x
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

In [82]:
a.grad.zero_()
def f(a):
    b = a * 2
    while b.norm() < 1000:
        print('case1')
        b = b * 2
    if b.sum() > 0:
        print('case2')
        c = b
    else:
        print('case3')
        c = 100 * b
    return c
a = torch.randn(size=(), requires_grad=True)
print(a, a.shape)
d = f(a)
d.backward()

a.grad == d / a
print(a.grad, d / a)

tensor(0.1282, requires_grad=True) torch.Size([])
case1
case1
case1
case1
case1
case1
case1
case1
case1
case1
case1
case1
case2
tensor(8192.) tensor(8192., grad_fn=<DivBackward0>)
