In [3]:
import torch
import torch.nn.functional as F
from torch import nn

class CenterenLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()
    
layer = CenterenLayer()
layer(torch.tensor([1.0, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [4]:
net = nn.Sequential(nn.Linear(8, 128), CenterenLayer())

Y = net(torch.rand(4, 8))
Y.mean()

tensor(-5.5879e-09, grad_fn=<MeanBackward0>)

In [7]:
class MyLinear(nn.Module):
    def __init__(self, in_unite, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_unite, units))
        self.bias = nn.Parameter(torch.randn(units))
    
    def forward(self, X):
        # 我们自己写就用右乘，更加好理解，和模型定义一致
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 0.9958,  1.1360, -0.6046],
        [-1.4241,  0.4335,  0.3939],
        [-0.7260, -0.6725, -0.7983],
        [ 1.9310, -0.3099,  0.5187],
        [-0.4276, -0.9602, -0.8340]], requires_grad=True)

In [8]:
linear(torch.rand(2, 5))

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.1105, 0.7243]])

In [9]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[0.],
        [0.]])