In [1]:
!nvidia-smi

Mon May 31 17:25:24 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 456.71       Driver Version: 461.33       CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 980 Ti WDDM  | 00000000:01:00.0  On |                  N/A |
|  0%   56C    P8   ERR! / ERR! |    783MiB /  6144MiB |      9%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU  

In [5]:
import torch
from torch import nn

torch.device('cpu'), torch.cuda.device('cuda'), torch.cuda.device('cuda:0'), torch.cuda.device('cuda:1'), torch.cuda.device('cuda:100')

(device(type='cpu'),
 <torch.cuda.device at 0x1bb00c98f40>)

In [15]:
torch.cuda.device_count()

0

In [18]:
def try_gpu(i=0):
    if torch.cuda.device_count() >= i + 1:
        return torch.device(f'cuda:{i}')
    return torch.device('cpu')

def try_all_gpus():
    devices = [
        torch.device(f'cuda:{i}') for i in range(torch.cuda.device_count())
    ]
    print(devices)
    return devices if devices else [torch.device('cpu')]

try_gpu(), try_gpu(10), try_all_gpus()

[]


(device(type='cpu'), device(type='cpu'), [device(type='cpu')])

In [19]:
x = torch.tensor([1, 2, 3])
x.device

device(type='cpu')

In [20]:
X = torch.ones(2, 3, device=try_gpu())
X

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [21]:
Y = torch.rand(2, 3, device=try_gpu(1))
Y

tensor([[0.5970, 0.4194, 0.2474],
        [0.4116, 0.0963, 0.8909]])

In [22]:
Z = X.cuda(1)
print(X)
print(Z)

AssertionError: Torch not compiled with CUDA enabled

In [23]:
Y + Z

NameError: name 'Z' is not defined

In [ ]:
Z.cuda(1) is Z

In [24]:
net = nn.Sequential(nn.Linear(3, 1))
net = net.to(device=try_gpu())

net(X)

tensor([[-0.7878],
        [-0.7878]], grad_fn=<AddmmBackward>)

In [25]:
net[0].weight.data.device

device(type='cpu')